server:
  port: 8081

spring:
  cache:
    type: redis
  data:
    redis:
      port: 6379
      host: localhost
  datasource:
    url: jdbc:postgresql://localhost:5432/db_api_cadastro_notas
    hikari:
      username: notas_user
      password: notas_user_passwd
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      use_jdbc_metadata_defaults: false
      hibernate:
        format_sql: true
  flyway:
    locations: classpath:db/migration



