CREATE TABLE USUARIO
(
    id    BIGINT       NOT NULL,
    nome  VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);
CREATE SEQUENCE usuario_seq START WITH 1 INCREMENT BY 1;